import { orderByName } from "../functions";

const provincias = [
  { departamento_id: 1, id: 101, name: "CHACHAPOYAS" },
  { departamento_id: 1, id: 102, name: "BAGUA" },
  { departamento_id: 1, id: 103, name: "BONGARA" },
  { departamento_id: 1, id: 104, name: "CONDORCANQUI" },
  { departamento_id: 1, id: 105, name: "LUYA" },
  { departamento_id: 1, id: 106, name: "RODRIGUEZ DE MENDOZA" },
  { departamento_id: 1, id: 107, name: "UTCUBAMBA" },
  { departamento_id: 2, id: 201, name: "HUARAZ" },
  { departamento_id: 2, id: 202, name: "AIJA" },
  { departamento_id: 2, id: 203, name: "ANTONIO RAYMONDI" },
  { departamento_id: 2, id: 204, name: "ASUNCION" },
  { departamento_id: 2, id: 205, name: "BOLOGNESI" },
  { departamento_id: 2, id: 206, name: "CARHUAZ" },
  { departamento_id: 2, id: 207, name: "CARLOS FERMIN FITZCARRALD" },
  { departamento_id: 2, id: 208, name: "CASMA" },
  { departamento_id: 2, id: 209, name: "CORONGO" },
  { departamento_id: 2, id: 210, name: "HUARI" },
  { departamento_id: 2, id: 211, name: "HUARMEY" },
  { departamento_id: 2, id: 212, name: "HUAYLAS" },
  { departamento_id: 2, id: 213, name: "MARISCAL LUZURIAGA" },
  { departamento_id: 2, id: 214, name: "OCROS" },
  { departamento_id: 2, id: 215, name: "PALLASCA" },
  { departamento_id: 2, id: 216, name: "POMABAMBA" },
  { departamento_id: 2, id: 217, name: "RECUAY" },
  { departamento_id: 2, id: 218, name: "SANTA" },
  { departamento_id: 2, id: 219, name: "SIHUAS" },
  { departamento_id: 2, id: 220, name: "YUNGAY" },
  { departamento_id: 3, id: 301, name: "ABANCAY" },
  { departamento_id: 3, id: 302, name: "ANDAHUAYLAS" },
  { departamento_id: 3, id: 303, name: "ANTABAMBA" },
  { departamento_id: 3, id: 304, name: "AYMARAES" },
  { departamento_id: 3, id: 305, name: "COTABAMBAS" },
  { departamento_id: 3, id: 306, name: "CHINCHEROS" },
  { departamento_id: 3, id: 307, name: "GRAU" },
  { departamento_id: 4, id: 401, name: "AREQUIPA" },
  { departamento_id: 4, id: 402, name: "CAMANA" },
  { departamento_id: 4, id: 403, name: "CARAVELI" },
  { departamento_id: 4, id: 404, name: "CASTILLA" },
  { departamento_id: 4, id: 405, name: "CAYLLOMA" },
  { departamento_id: 4, id: 406, name: "CONDESUYOS" },
  { departamento_id: 4, id: 407, name: "ISLAY" },
  { departamento_id: 4, id: 408, name: "LA UNION" },
  { departamento_id: 5, id: 501, name: "HUAMANGA" },
  { departamento_id: 5, id: 502, name: "CANGALLO" },
  { departamento_id: 5, id: 503, name: "HUANCA SANCOS" },
  { departamento_id: 5, id: 504, name: "HUANTA" },
  { departamento_id: 5, id: 505, name: "LA MAR" },
  { departamento_id: 5, id: 506, name: "LUCANAS" },
  { departamento_id: 5, id: 507, name: "PARINACOCHAS" },
  { departamento_id: 5, id: 508, name: "PAUCAR DEL SARA SARA" },
  { departamento_id: 5, id: 509, name: "SUCRE" },
  { departamento_id: 5, id: 510, name: "VICTOR FAJARDO" },
  { departamento_id: 5, id: 511, name: "VILCAS HUAMAN" },
  { departamento_id: 6, id: 601, name: "CAJAMARCA" },
  { departamento_id: 6, id: 602, name: "CAJABAMBA" },
  { departamento_id: 6, id: 603, name: "CELENDIN" },
  { departamento_id: 6, id: 604, name: "CHOTA" },
  { departamento_id: 6, id: 605, name: "CONTUMAZA" },
  { departamento_id: 6, id: 606, name: "CUTERVO" },
  { departamento_id: 6, id: 607, name: "HUALGAYOC" },
  { departamento_id: 6, id: 608, name: "JAEN" },
  { departamento_id: 6, id: 609, name: "SAN IGNACIO" },
  { departamento_id: 6, id: 610, name: "SAN MARCOS" },
  { departamento_id: 6, id: 611, name: "SAN MIGUEL" },
  { departamento_id: 6, id: 612, name: "SAN PABLO" },
  { departamento_id: 6, id: 613, name: "SANTA CRUZ" },
  { departamento_id: 7, id: 701, name: "CALLAO" },
  { departamento_id: 8, id: 801, name: "CUSCO" },
  { departamento_id: 8, id: 802, name: "ACOMAYO" },
  { departamento_id: 8, id: 803, name: "ANTA" },
  { departamento_id: 8, id: 804, name: "CALCA" },
  { departamento_id: 8, id: 805, name: "CANAS" },
  { departamento_id: 8, id: 806, name: "CANCHIS" },
  { departamento_id: 8, id: 807, name: "CHUMBIVILCAS" },
  { departamento_id: 8, id: 808, name: "ESPINAR" },
  { departamento_id: 8, id: 809, name: "LA CONVENCION" },
  { departamento_id: 8, id: 810, name: "PARURO" },
  { departamento_id: 8, id: 811, name: "PAUCARTAMBO" },
  { departamento_id: 8, id: 812, name: "QUISPICANCHI" },
  { departamento_id: 8, id: 813, name: "URUBAMBA" },
  { departamento_id: 9, id: 901, name: "HUANCAVELICA" },
  { departamento_id: 9, id: 902, name: "ACOBAMBA" },
  { departamento_id: 9, id: 903, name: "ANGARAES" },
  { departamento_id: 9, id: 904, name: "CASTROVIRREYNA" },
  { departamento_id: 9, id: 905, name: "CHURCAMPA" },
  { departamento_id: 9, id: 906, name: "HUAYTARA" },
  { departamento_id: 9, id: 907, name: "TAYACAJA" },
  { departamento_id: 10, id: 1001, name: "HUANUCO" },
  { departamento_id: 10, id: 1002, name: "AMBO" },
  { departamento_id: 10, id: 1003, name: "DOS DE MAYO" },
  { departamento_id: 10, id: 1004, name: "HUACAYBAMBA" },
  { departamento_id: 10, id: 1005, name: "HUAMALIES" },
  { departamento_id: 10, id: 1006, name: "LEONCIO PRADO" },
  { departamento_id: 10, id: 1007, name: "MARAÑON" },
  { departamento_id: 10, id: 1008, name: "PACHITEA" },
  { departamento_id: 10, id: 1009, name: "PUERTO INCA" },
  { departamento_id: 10, id: 1010, name: "LAURICOCHA" },
  { departamento_id: 10, id: 1011, name: "YAROWILCA" },
  { departamento_id: 11, id: 1101, name: "ICA" },
  { departamento_id: 11, id: 1102, name: "CHINCHA" },
  { departamento_id: 11, id: 1103, name: "NAZCA" },
  { departamento_id: 11, id: 1104, name: "PALPA" },
  { departamento_id: 11, id: 1105, name: "PISCO" },
  { departamento_id: 12, id: 1201, name: "HUANCAYO" },
  { departamento_id: 12, id: 1202, name: "CONCEPCION" },
  { departamento_id: 12, id: 1203, name: "CHANCHAMAYO" },
  { departamento_id: 12, id: 1204, name: "JAUJA" },
  { departamento_id: 12, id: 1205, name: "JUNIN" },
  { departamento_id: 12, id: 1206, name: "SATIPO" },
  { departamento_id: 12, id: 1207, name: "TARMA" },
  { departamento_id: 12, id: 1208, name: "YAULI" },
  { departamento_id: 12, id: 1209, name: "CHUPACA" },
  { departamento_id: 13, id: 1301, name: "TRUJILLO" },
  { departamento_id: 13, id: 1302, name: "ASCOPE" },
  { departamento_id: 13, id: 1303, name: "BOLIVAR" },
  { departamento_id: 13, id: 1304, name: "CHEPEN" },
  { departamento_id: 13, id: 1305, name: "JULCAN" },
  { departamento_id: 13, id: 1306, name: "OTUZCO" },
  { departamento_id: 13, id: 1307, name: "PACASMAYO" },
  { departamento_id: 13, id: 1308, name: "PATAZ" },
  { departamento_id: 13, id: 1309, name: "SANCHEZ CARRION" },
  { departamento_id: 13, id: 1310, name: "SANTIAGO DE CHUCO" },
  { departamento_id: 13, id: 1311, name: "GRAN CHIMU" },
  { departamento_id: 13, id: 1312, name: "VIRU" },
  { departamento_id: 14, id: 1401, name: "CHICLAYO" },
  { departamento_id: 14, id: 1402, name: "FERREÑAFE" },
  { departamento_id: 14, id: 1403, name: "LAMBAYEQUE" },
  { departamento_id: 15, id: 1501, name: "LIMA" },
  { departamento_id: 15, id: 1502, name: "BARRANCA" },
  { departamento_id: 15, id: 1503, name: "CAJATAMBO" },
  { departamento_id: 15, id: 1504, name: "CANTA" },
  { departamento_id: 15, id: 1505, name: "CAÑETE" },
  { departamento_id: 15, id: 1506, name: "HUARAL" },
  { departamento_id: 15, id: 1507, name: "HUAROCHIRI" },
  { departamento_id: 15, id: 1508, name: "HUAURA" },
  { departamento_id: 15, id: 1509, name: "OYON" },
  { departamento_id: 15, id: 1510, name: "YAUYOS" },
  { departamento_id: 16, id: 1601, name: "MAYNAS" },
  { departamento_id: 16, id: 1602, name: "ALTO AMAZONAS" },
  { departamento_id: 16, id: 1603, name: "LORETO" },
  { departamento_id: 16, id: 1604, name: "MARISCAL RAMON CASTILLA" },
  { departamento_id: 16, id: 1605, name: "REQUENA" },
  { departamento_id: 16, id: 1606, name: "UCAYALI" },
  { departamento_id: 16, id: 1607, name: "DATEM DEL MARAÑON" },
  { departamento_id: 16, id: 1608, name: "PUTUMAYO" },
  { departamento_id: 17, id: 1701, name: "TAMBOPATA" },
  { departamento_id: 17, id: 1702, name: "MANU" },
  { departamento_id: 17, id: 1703, name: "TAHUAMANU" },
  { departamento_id: 18, id: 1801, name: "MARISCAL NIETO" },
  { departamento_id: 18, id: 1802, name: "GENERAL SANCHEZ CERRO" },
  { departamento_id: 18, id: 1803, name: "ILO" },
  { departamento_id: 19, id: 1901, name: "PASCO" },
  { departamento_id: 19, id: 1902, name: "DANIEL ALCIDES CARRION" },
  { departamento_id: 19, id: 1903, name: "OXAPAMPA" },
  { departamento_id: 20, id: 2001, name: "PIURA" },
  { departamento_id: 20, id: 2002, name: "AYABACA" },
  { departamento_id: 20, id: 2003, name: "HUANCABAMBA" },
  { departamento_id: 20, id: 2004, name: "MORROPON" },
  { departamento_id: 20, id: 2005, name: "PAITA" },
  { departamento_id: 20, id: 2006, name: "SULLANA" },
  { departamento_id: 20, id: 2007, name: "TALARA" },
  { departamento_id: 20, id: 2008, name: "SECHURA" },
  { departamento_id: 21, id: 2101, name: "PUNO" },
  { departamento_id: 21, id: 2102, name: "AZANGARO" },
  { departamento_id: 21, id: 2103, name: "CARABAYA" },
  { departamento_id: 21, id: 2104, name: "CHUCUITO" },
  { departamento_id: 21, id: 2105, name: "EL COLLAO" },
  { departamento_id: 21, id: 2106, name: "HUANCANE" },
  { departamento_id: 21, id: 2107, name: "LAMPA" },
  { departamento_id: 21, id: 2108, name: "MELGAR" },
  { departamento_id: 21, id: 2109, name: "MOHO" },
  { departamento_id: 21, id: 2110, name: "SAN ANTONIO DE PUTINA" },
  { departamento_id: 21, id: 2111, name: "SAN ROMAN" },
  { departamento_id: 21, id: 2112, name: "SANDIA" },
  { departamento_id: 21, id: 2113, name: "YUNGUYO" },
  { departamento_id: 22, id: 2201, name: "MOYOBAMBA" },
  { departamento_id: 22, id: 2202, name: "BELLAVISTA" },
  { departamento_id: 22, id: 2203, name: "EL DORADO" },
  { departamento_id: 22, id: 2204, name: "HUALLAGA" },
  { departamento_id: 22, id: 2205, name: "LAMAS" },
  { departamento_id: 22, id: 2206, name: "MARISCAL CACERES" },
  { departamento_id: 22, id: 2207, name: "PICOTA" },
  { departamento_id: 22, id: 2208, name: "RIOJA" },
  { departamento_id: 22, id: 2209, name: "SAN MARTIN" },
  { departamento_id: 22, id: 2210, name: "TOCACHE" },
  { departamento_id: 23, id: 2301, name: "TACNA" },
  { departamento_id: 23, id: 2302, name: "CANDARAVE" },
  { departamento_id: 23, id: 2303, name: "JORGE BASADRE" },
  { departamento_id: 23, id: 2304, name: "TARATA" },
  { departamento_id: 24, id: 2401, name: "TUMBES" },
  { departamento_id: 24, id: 2402, name: "CONTRALMIRANTE VILLAR" },
  { departamento_id: 24, id: 2403, name: "ZARUMILLA" },
  { departamento_id: 25, id: 2501, name: "CORONEL PORTILLO" },
  { departamento_id: 25, id: 2502, name: "ATALAYA" },
  { departamento_id: 25, id: 2503, name: "PADRE ABAD" },
  { departamento_id: 25, id: 2504, name: "PURUS" },
];

orderByName(provincias);

export { provincias };
